Jenkinsfile, src/main/java/org/folio/rest/impl/LoginAPI.java
Enable lint-raml with CI.
Developers can run the same script locally at `../folio-tools/lint-raml/lint_raml_cop.py`
See the [guides/raml-cop](https://dev.folio.org/guides/raml-cop/).
Also the api.yml configuration has a commented-out entry which is ready for the expected new layout of "ramls" and "ramls/raml-util".
=> FOLIO-1027 enable lint-raml jenkins

src/main/java/org/folio/rest/impl/LoginAPI.java, src/main/java/org/folio/util/LoginAttemptsHelper.java
1. Fixed an issue with getting error after three and five failed attempts to login.
2. Fixed error codes, set "username.incorrect" for incorrect username and "password.incorrect" for incorrect password.
Jira ticket: [MODLOGIN-88](https://issues.folio.org/browse/MODLOGIN-88)
=> MODLOGIN-88: Incorrect error codes returns from BE

src/main/java/org/folio/services/impl/PasswordStorageServiceImpl.java, src/test/java/org/folio/logintest/UpdateCredentialsHistoryTest.java
Explicitly close database connection, because it is not closed and database stops responding when connection pull becomes full.
=> MODLOGIN-86: Close database connection

ramls/password.json, src/main/java/org/folio/services/impl/PasswordStorageServiceImpl.java, src/test/java/org/folio/logintest/PasswordRepeatabilityValidationTest.java
**Purpose**
Update `mod-login` API contract to implement a user password reset by link.
Resolves: [MODLOGIN-114](https://issues.folio.org/browse/MODLOGIN-114)
=> MODLOGIN-114 Change the implementation of password checking for repeatability [Reset passwords: user can reset password by link]

descriptors/ModuleDescriptor-template.json, ramls/login.raml
Changes in the version of the mod-login https://github.com/folio-org/mod-login/pull/64 affect changes in the modules: 
-  'edge-oai-pmh',
-  'edge-orders',
-  'edge-patron',
-  'edge-rtac',
-  'ui-users',
-  'mod-users-bl'
-  'edge-sip2'
-  'mod-login'
=> Raising the interface version related to mod-login API breaking change

src/main/java/org/folio/rest/impl/InitAPIs.java, src/main/java/org/folio/rest/impl/LoginAPI.java, src/main/java/org/folio/services/impl/ConfigurationServiceImpl.java, src/main/java/org/folio/services/impl/PasswordStorageServiceImpl.java, src/main/java/org/folio/util/Constants.java, src/main/java/org/folio/util/LoginAttemptsHelper.java
Moved the login API's `HttpClient` creation to `InitAPIs`. The client is stored in the vertx context shared by the APIs. A static `HttpClient` singleton would not work well for testing without modifying the security model to reset the static. Cleaning up the client seemed challenging without refactoring much of the code.
A couple things worth noting:
1. I moved the `lookup.timeout` `HttpClientOptions` as well. However, I see we are using the same value for both the connect timeout and the idle timeout. The value itself defaults to `1000` which would suggest milliseconds and the connect timeout is in ms, however, the idle timeout unit defaults to seconds. This may not be the intended usage here and should probably be looked into at some point.
1. Also, at some point, …
=> MODLOGIN-116: reduce HttpClient creation to one time

Jenkinsfile
Enables kubeDeploy step on buildMvn pipeline to deploy container to CI kubernetes cluster on release/snapshot builds for FOLIO-2256.
=> publish container to ci kubernetes when snap/release build

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
=> MODLOGIN-121 FOLIO-2358 manage container memory

src/main/java/org/folio/rest/impl/LoginAPI.java, src/test/java/org/folio/logintest/LoginAttemptsTest.java
If /authn/credentials POST API is called with JSON that contains a valid "username" or "userId" for a user that does not have credentials, but the JSON does not contain a "password" field, the API returns 500.
Implement validation that will prevent NullPointerException in mod-login in AuthUti.calculateHash().
422 error should be returned with an error message.
Resolves [MODLOGIN-24](https://issues.folio.org/browse/MODLOGIN-24)
=> MODLOGIN-24 add validation for missed password

pom.xml, src/main/java/org/folio/rest/impl/InitAPIs.java, src/main/java/org/folio/rest/impl/LoginAPI.java, src/main/java/org/folio/services/impl/ConfigurationServiceImpl.java, src/main/java/org/folio/services/impl/LogStorageServiceImpl.java, src/main/java/org/folio/services/impl/PasswordStorageServiceImpl.java, src/main/java/org/folio/util/Constants.java, src/main/java/org/folio/util/LoginAttemptsHelper.java, src/main/java/org/folio/util/WebClientFactory.java, src/test/java/org/folio/logintest/CredentialExistenceTest.java, src/test/java/org/folio/logintest/EventsLoggingTests.java, src/test/java/org/folio/logintest/LoginAttemptsTest.java, src/test/java/org/folio/logintest/PasswordRepeatabilityValidationTest.java, src/test/java/org/folio/logintest/PasswordResetActionTest.java, src/test/java/org/folio/logintest/RestVerticleTest.java, src/test/java/org/folio/logintest/TestUtil.java, src/test/java/org/folio/logintest/UpdateCredentialsHistoryTest.java, src/test/java/org/folio/logintest/UserMock.java, src/test/java/org/folio/util/WebClientFactoryTest.java
Upgrade to RMB 30.0.0 in preparation for the Q2/Goldenrod release.
See [MODLOGIN-127](https://issues.folio.org/browse/MODLOGIN-127)
* CompletableFuture -> Promise
* HttpClient -> WebClient
- new dependency in pom.xml
* PostgresClient changes
* Unit tests were updated, including one bug in the mock server (only handing PUT /users/<id> for a single particular userId.  
* Move away from storing/retrieving the HttpClient on the VertxContext.  Instead use a Bill Pugh singleton.  Creating and putting a client on the VertxContext in InitAPI and then accessing it later on was unreliable - not sure what happened as it appeared to work before.  I think this is straightforward and reliable though.
* [RMB Upgrade Guide](https://github.com/folio-org/raml-module-builder/blob/v30.0.0/doc/upgrading.md#ver …
=> MODLOGIN-127 Upgrade to RMB 30.0.0

ramls/login.raml, src/main/java/org/folio/rest/impl/LoginAPI.java, src/test/java/org/folio/logintest/RestVerticleTest.java
Per comments in [MODLOGIN-129](https://issues.folio.org/browse/MODLOGIN-129) made after the [original work](https://github.com/folio-org/mod-login/pull/83) was merged, we want to consolidate password validation into mod-password-validator.
Rules already exist in mod-password-validator work which restrict the use of whitespace.  If needed we can file JIRAs for additional restrictions (e.g. for trailing/leading whitespace)
=> MODLOGIN-129 - back out password requirement: can't be all whitespace

NEWS.md, pom.xml
Release v7.0.0.
The major version bump is due to several breaking changes made to the /authn/credentials and related endpoints, 
See: https://issues.folio.org/browse/MODLOGIN-126
=> MODLOGIN-126 - Release  v7.0.0

pom.xml
RMB 30.2.6 release notes: https://github.com/folio-org/raml-module-builder/releases/tag/v30.2.6
* [RMB-701](https://issues.folio.org/browse/RMB-701) Update to [Vert.x 3.9.2](https://github.com/vert-x3/wiki/wiki/3.9.2-Release-Notes), fixing WebClient request timeout races
* [RMB-700](https://issues.folio.org/browse/RMB-700) NPE when RestVerticle calls LogUtil.formatStatsLogMessage
* [RMB-677](https://issues.folio.org/browse/RMB-677) Close PostgreSQL connection after invalid CQL failure
=> MODLOGIN-135: Upgrade raml-module-builder (RMB) to 30.2.6

pom.xml, src/test/java/org/folio/services/impl/PasswordResetActionTest.java
Most notable fixes:
* [RMB-740](https://issues.folio.org/browse/RMB-740) Use FOLIO fork of vertx-sql-client and vertx-pg-client with
the following two patches
* [RMB-739](https://issues.folio.org/browse/RMB-739) Make RMB's DB\_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* [FOLIO-2840](https://issues.folio.org/browse/FOLIO-2840) Fix duplicate names causing 'prepared statement "XYZ" already exists'
* [RMB-738](https://issues.folio.org/browse/RMB-738) Upgrade to Vert.x 3.9.4, most notable fixed bug: RowStream fetch
can close prematurely the stream https://github.com/eclipse-vertx/vertx-sql-client/issues/778
=> MODLOGIN-138: Upgrade to RMB 31.1.3 and Vert.x 3.9.4

pom.xml
See RMB-744 for details.
Upgrading mod-login from Q2 (Goldenrod) to mod-login-7.1.0 fails with
"tuple concurrently updated" when executing "REVOKE ALL PRIVILEGES
ON SCHEMA public FROM module_schema".
RMB-744 provides a potential fix.
To test this fix we temporarily try RMB-31.2.0-SNAPSHOT on mod-login master.
=> MODLOGIN-139: Q2 to Q3 upgrade - "tuple concurrently updated" on REVOKE

pom.xml
RMB 31.1.5 provides
* RMB-750 Change lock for "tuple concurrently updated" when upgrading Q2 to Q3 (REVOKE)
=> MODLOGIN-140: Upgrade to RMB 31.1.5

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/rest/impl/LoginAPI.java, src/main/java/org/folio/services/impl/ConfigurationServiceImpl.java, src/main/java/org/folio/services/impl/PasswordStorageServiceImpl.java, src/main/java/org/folio/util/LoginAttemptsHelper.java, src/test/java/org/folio/logintest/RestVerticleTest.java, src/test/java/org/folio/logintest/UserMock.java
https://issues.folio.org/browse/MODLOGIN-168
The user object is not sent in https://github.com/folio-org/mod-login/blob/v7.5.0/src/main/java/org/folio/util/LoginAttemptsHelper.java#L265
On top of the bug fix, simplify WebClient usage:
Change promise to map in WebClient calls.
sendJsonObject automatically sends content type application/json
And content-type is not necessary for GETs (send()).
Since RMB 32.2.0, Accept is no longer necessary in most cases.
=> Fix empty PUT /users/id MODLOGIN-168

descriptors/ModuleDescriptor-template.json
Requiring it is optional as in boostrap process you need
to specify credentials for admin user - before mod-authtoken
is enabled (and interface authtoken).
=> Optional dependency on authtoken 2.0 MODLOGIN-155

src/main/java/org/folio/util/LoginAttemptsHelper.java
https://issues.folio.org/browse/MODLOGIN-184
Don't think it's necessary to CQL encode the `code` term itself as the code is usually only dots and alphanumerics.
=> Fix CQL query encoded incorrectly MODLOGIN-184

README.md
The configuration entries used by this module are not (as far as I can tell) documented anywhere.  
Update the README:
* Add a table with the various configuration entries used by this module, including:
* Which fields of the configuration entry are used to identify them (module, code, configName, etc.)
* Default values
* Description of each
* Add clarifying remarks to the section about "Module properties".
=> Document config entries

README.md
One configuration entry was missed in #141.  There was also feedback provided in slack which suggests that the case of the first 3 column headers should be changed to match the fields used by mod-configuration.
=> Document missing configuration entry in README

pom.xml
Adding the reference in the pom to log4j before vertx seems to be needed for the container to start. It will build without it, but [failed when the docker image started for the health check](https://jenkins-aws.indexdata.com/blue/organizations/jenkins/folio-org%2Fmod-login/detail/MODLOGIN-218/1/pipeline).
=> MODLOGIN-218: Update dependencies for Poppy
